-- FrancoTrades Mentoria - estrutura financeira
-- Não contém dados pessoais de mentorados.

create table if not exists public.mentorship_financials (
  id uuid primary key default gen_random_uuid(),
  profile_id uuid null references public.profiles(id) on delete set null,
  nome text not null,
  email text not null,
  valor_total numeric(12,2) not null default 0,
  moeda text not null default 'BRL' check (moeda in ('BRL','USD')),
  observacoes text,
  quantidade_sessoes integer not null default 12,
  sessoes_concluidas_importadas integer not null default 0,
  origem text not null default 'manual',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint mentorship_financials_email_unique unique (email)
);

create index if not exists mentorship_financials_profile_id_idx
  on public.mentorship_financials(profile_id);

create table if not exists public.mentorship_payments (
  id bigint generated by default as identity primary key,
  mentorship_id uuid not null references public.mentorship_financials(id) on delete cascade,
  numero_parcela integer not null,
  valor numeric(12,2) not null default 0,
  vencimento date,
  paga boolean not null default false,
  data_pagamento date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint mentorship_payments_unique_installment unique (mentorship_id, numero_parcela)
);

create index if not exists mentorship_payments_mentorship_id_idx
  on public.mentorship_payments(mentorship_id);

create table if not exists public.mentorship_settings (
  id integer primary key default 1 check (id = 1),
  meta_faturamento_brl numeric(12,2) not null default 120000,
  updated_at timestamptz not null default now()
);

insert into public.mentorship_settings (id, meta_faturamento_brl)
values (1, 120000)
on conflict (id) do nothing;

alter table public.mentorship_financials enable row level security;
alter table public.mentorship_payments enable row level security;
alter table public.mentorship_settings enable row level security;

drop policy if exists "admin_select_mentorship_financials" on public.mentorship_financials;
drop policy if exists "admin_insert_mentorship_financials" on public.mentorship_financials;
drop policy if exists "admin_update_mentorship_financials" on public.mentorship_financials;
drop policy if exists "admin_delete_mentorship_financials" on public.mentorship_financials;

create policy "admin_select_mentorship_financials"
on public.mentorship_financials
for select
to authenticated
using (public.is_admin());

create policy "admin_insert_mentorship_financials"
on public.mentorship_financials
for insert
to authenticated
with check (public.is_admin());

create policy "admin_update_mentorship_financials"
on public.mentorship_financials
for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy "admin_delete_mentorship_financials"
on public.mentorship_financials
for delete
to authenticated
using (public.is_admin());

drop policy if exists "admin_select_mentorship_payments" on public.mentorship_payments;
drop policy if exists "admin_insert_mentorship_payments" on public.mentorship_payments;
drop policy if exists "admin_update_mentorship_payments" on public.mentorship_payments;
drop policy if exists "admin_delete_mentorship_payments" on public.mentorship_payments;

create policy "admin_select_mentorship_payments"
on public.mentorship_payments
for select
to authenticated
using (public.is_admin());

create policy "admin_insert_mentorship_payments"
on public.mentorship_payments
for insert
to authenticated
with check (public.is_admin());

create policy "admin_update_mentorship_payments"
on public.mentorship_payments
for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy "admin_delete_mentorship_payments"
on public.mentorship_payments
for delete
to authenticated
using (public.is_admin());

drop policy if exists "admin_select_mentorship_settings" on public.mentorship_settings;
drop policy if exists "admin_update_mentorship_settings" on public.mentorship_settings;
drop policy if exists "admin_insert_mentorship_settings" on public.mentorship_settings;

create policy "admin_select_mentorship_settings"
on public.mentorship_settings
for select
to authenticated
using (public.is_admin());

create policy "admin_update_mentorship_settings"
on public.mentorship_settings
for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy "admin_insert_mentorship_settings"
on public.mentorship_settings
for insert
to authenticated
with check (public.is_admin());
