-- FrancoTrades Mentoria - estrutura de lembretes de parcelas
-- Execute este arquivo no SQL Editor do Supabase.

create table if not exists public.payment_reminder_log (
  id bigint generated by default as identity primary key,
  payment_id bigint not null references public.mentorship_payments(id) on delete cascade,
  mentorship_id uuid not null references public.mentorship_financials(id) on delete cascade,
  reminder_type text not null check (
    reminder_type in (
      '5_days_before',
      '1_day_before',
      'due_today',
      '3_days_overdue'
    )
  ),
  recipient_email text not null,
  sent_at timestamptz not null default now(),
  provider_message_id text,
  provider_response jsonb,
  constraint payment_reminder_log_unique
    unique (payment_id, reminder_type)
);

create index if not exists payment_reminder_log_payment_idx
  on public.payment_reminder_log(payment_id);

create index if not exists payment_reminder_log_mentorship_idx
  on public.payment_reminder_log(mentorship_id);

alter table public.payment_reminder_log enable row level security;

drop policy if exists "admin_select_payment_reminder_log"
  on public.payment_reminder_log;

create policy "admin_select_payment_reminder_log"
on public.payment_reminder_log
for select
to authenticated
using (public.is_admin());
