-- FrancoTrades Mentoria - lembretes automáticos de parcelas
-- Execute este arquivo no SQL Editor do Supabase depois de publicar a Edge Function
-- e cadastrar os secrets RESEND_API_KEY, REMINDER_FROM_EMAIL e REMINDER_CRON_SECRET.

create table if not exists public.payment_reminder_log (
  id bigint generated by default as identity primary key,
  payment_id bigint not null references public.mentorship_payments(id) on delete cascade,
  mentorship_id uuid not null references public.mentorship_financials(id) on delete cascade,
  reminder_type text not null check (reminder_type in ('5_days_before','1_day_before','due_today','3_days_overdue')),
  recipient_email text not null,
  sent_at timestamptz not null default now(),
  provider_message_id text,
  provider_response jsonb,
  constraint payment_reminder_log_unique unique (payment_id, reminder_type)
);

create index if not exists payment_reminder_log_payment_idx
  on public.payment_reminder_log(payment_id);

create index if not exists payment_reminder_log_mentorship_idx
  on public.payment_reminder_log(mentorship_id);

alter table public.payment_reminder_log enable row level security;

drop policy if exists "admin_select_payment_reminder_log"
  on public.payment_reminder_log;

create policy "admin_select_payment_reminder_log"
on public.payment_reminder_log
for select
to authenticated
using (public.is_admin());

-- Cron: 09:00 no horário de Brasília (12:00 UTC).
-- Antes de executar a parte abaixo:
-- 1) publique a função payment-reminders;
-- 2) crie no Vault os secrets project_url, publishable_key e reminder_cron_secret;
-- 3) use no reminder_cron_secret o MESMO valor configurado como REMINDER_CRON_SECRET na Edge Function.

create extension if not exists pg_cron with schema pg_catalog;
create extension if not exists pg_net with schema extensions;

-- Remova o job anterior, caso exista.
do $$
begin
  perform cron.unschedule(jobid)
  from cron.job
  where jobname = 'francotrades-payment-reminders';
exception
  when others then
    null;
end $$;

select cron.schedule(
  'francotrades-payment-reminders',
  '0 12 * * *',
  $$
  select
    net.http_post(
      url := (
        select decrypted_secret
        from vault.decrypted_secrets
        where name = 'project_url'
        limit 1
      ) || '/functions/v1/payment-reminders',
      headers := jsonb_build_object(
        'Content-Type', 'application/json',
        'apikey', (
          select decrypted_secret
          from vault.decrypted_secrets
          where name = 'publishable_key'
          limit 1
        ),
        'x-cron-secret', (
          select decrypted_secret
          from vault.decrypted_secrets
          where name = 'reminder_cron_secret'
          limit 1
        )
      ),
      body := jsonb_build_object(
        'source', 'supabase-cron',
        'run_at', now()
      ),
      timeout_milliseconds := 15000
    ) as request_id;
  $$
);
