-- FrancoTrades Mentoria — Diário de Trade privado dos mentorados
-- Execute UMA VEZ no SQL Editor do Supabase.
--
-- Objetivos:
-- 1) Cada mentorado ativo acessa somente as próprias contas, trades, prints e comentários do mentor.
-- 2) Administradores acessam todos os mentorados, inclusive após expiração/inativação.
-- 3) O histórico NÃO é apagado quando o acesso do aluno termina.
-- 4) O diário pessoal do administrador não é armazenado nestas tabelas.

create or replace function public.has_active_mentorship_access(
  target_user uuid default auth.uid()
)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles p
    where p.id = target_user
      and p.role = 'aluno'
      and p.status = 'ativo'
      and (
        p.data_expiracao is null
        or p.data_expiracao >= current_date
      )
  );
$$;

create or replace function public.can_access_student_trade_journal(
  target_student uuid
)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select
    public.is_admin()
    or (
      auth.uid() = target_student
      and public.has_active_mentorship_access(target_student)
    );
$$;


create table if not exists public.student_trade_accounts (
  id bigint generated by default as identity primary key,
  student_id uuid not null references public.profiles(id),
  name text not null,
  broker text,
  account_type text not null default 'personal'
    check (account_type in ('personal','prop','simulator')),
  prop_firm text,
  currency text not null default 'USD'
    check (currency in ('USD','BRL')),
  starting_balance numeric(18,2) not null default 0,
  account_size numeric(18,2),
  account_stage text not null default 'new'
    check (account_stage in ('new','existing')),
  current_balance numeric(18,2),
  drawdown_remaining numeric(18,2),
  max_drawdown numeric(18,2),
  profit_target numeric(18,2),
  daily_loss_limit numeric(18,2),
  consistency_rule numeric(8,2),
  rules jsonb not null default '{}'::jsonb,
  active boolean not null default true,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists student_trade_accounts_student_idx
  on public.student_trade_accounts(student_id, active, created_at desc);

alter table public.student_trade_accounts enable row level security;

drop policy if exists "Trade accounts private access" on public.student_trade_accounts;
create policy "Trade accounts private access"
on public.student_trade_accounts
for select
to authenticated
using (public.can_access_student_trade_journal(student_id));

drop policy if exists "Trade accounts private insert" on public.student_trade_accounts;
create policy "Trade accounts private insert"
on public.student_trade_accounts
for insert
to authenticated
with check (
  public.can_access_student_trade_journal(student_id)
  and (
    public.is_admin()
    or student_id = auth.uid()
  )
);

drop policy if exists "Trade accounts private update" on public.student_trade_accounts;
create policy "Trade accounts private update"
on public.student_trade_accounts
for update
to authenticated
using (public.can_access_student_trade_journal(student_id))
with check (
  public.can_access_student_trade_journal(student_id)
  and (
    public.is_admin()
    or student_id = auth.uid()
  )
);


create table if not exists public.student_trades (
  id bigint generated by default as identity primary key,
  student_id uuid not null references public.profiles(id),
  account_id bigint references public.student_trade_accounts(id) on delete set null,
  trade_date date not null,
  symbol text not null,
  side text not null default 'long'
    check (side in ('long','short')),
  quantity numeric(18,4),
  entry_price numeric(18,6),
  exit_price numeric(18,6),
  pnl numeric(18,2) not null default 0,
  fees numeric(18,2) not null default 0,
  setup text,
  emotion text,
  rr numeric(12,4),
  mfe numeric(18,2),
  mae numeric(18,2),
  grade integer check (grade is null or (grade between 1 and 5)),
  notes text,
  source text not null default 'manual'
    check (source in ('manual','csv','thinkorswim','tradeify','other')),
  external_id text,
  raw_data jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists student_trades_student_date_idx
  on public.student_trades(student_id, trade_date desc, id desc);

create index if not exists student_trades_account_idx
  on public.student_trades(account_id, trade_date desc);

alter table public.student_trades enable row level security;

drop policy if exists "Student trades private access" on public.student_trades;
create policy "Student trades private access"
on public.student_trades
for select
to authenticated
using (public.can_access_student_trade_journal(student_id));

drop policy if exists "Student trades private insert" on public.student_trades;
create policy "Student trades private insert"
on public.student_trades
for insert
to authenticated
with check (
  public.can_access_student_trade_journal(student_id)
  and (
    public.is_admin()
    or student_id = auth.uid()
  )
);

drop policy if exists "Student trades private update" on public.student_trades;
create policy "Student trades private update"
on public.student_trades
for update
to authenticated
using (public.can_access_student_trade_journal(student_id))
with check (
  public.can_access_student_trade_journal(student_id)
  and (
    public.is_admin()
    or student_id = auth.uid()
  )
);

drop policy if exists "Student trades private delete" on public.student_trades;
create policy "Student trades private delete"
on public.student_trades
for delete
to authenticated
using (
  public.can_access_student_trade_journal(student_id)
  and (
    public.is_admin()
    or student_id = auth.uid()
  )
);


create table if not exists public.student_trade_attachments (
  id bigint generated by default as identity primary key,
  student_id uuid not null references public.profiles(id),
  trade_id bigint not null references public.student_trades(id) on delete cascade,
  storage_path text not null unique,
  file_name text not null,
  content_type text,
  file_size bigint,
  created_at timestamptz not null default now()
);

create index if not exists student_trade_attachments_trade_idx
  on public.student_trade_attachments(trade_id, created_at desc);

alter table public.student_trade_attachments enable row level security;

drop policy if exists "Trade attachments private access" on public.student_trade_attachments;
create policy "Trade attachments private access"
on public.student_trade_attachments
for select
to authenticated
using (public.can_access_student_trade_journal(student_id));

drop policy if exists "Trade attachments private insert" on public.student_trade_attachments;
create policy "Trade attachments private insert"
on public.student_trade_attachments
for insert
to authenticated
with check (
  public.can_access_student_trade_journal(student_id)
  and (
    public.is_admin()
    or student_id = auth.uid()
  )
);

drop policy if exists "Trade attachments private delete" on public.student_trade_attachments;
create policy "Trade attachments private delete"
on public.student_trade_attachments
for delete
to authenticated
using (
  public.can_access_student_trade_journal(student_id)
  and (
    public.is_admin()
    or student_id = auth.uid()
  )
);


create table if not exists public.student_trade_comments (
  id bigint generated by default as identity primary key,
  student_id uuid not null references public.profiles(id),
  trade_id bigint not null references public.student_trades(id) on delete cascade,
  author_id uuid not null default auth.uid() references public.profiles(id),
  comment text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists student_trade_comments_trade_idx
  on public.student_trade_comments(trade_id, created_at asc);

alter table public.student_trade_comments enable row level security;

drop policy if exists "Trade comments readable by student and admin" on public.student_trade_comments;
create policy "Trade comments readable by student and admin"
on public.student_trade_comments
for select
to authenticated
using (public.can_access_student_trade_journal(student_id));

drop policy if exists "Only admins create trade comments" on public.student_trade_comments;
create policy "Only admins create trade comments"
on public.student_trade_comments
for insert
to authenticated
with check (
  public.is_admin()
  and author_id = auth.uid()
);

drop policy if exists "Only admins update trade comments" on public.student_trade_comments;
create policy "Only admins update trade comments"
on public.student_trade_comments
for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Only admins delete trade comments" on public.student_trade_comments;
create policy "Only admins delete trade comments"
on public.student_trade_comments
for delete
to authenticated
using (public.is_admin());


create or replace function public.set_student_trade_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_student_trade_accounts_updated_at
  on public.student_trade_accounts;
create trigger set_student_trade_accounts_updated_at
before update on public.student_trade_accounts
for each row execute function public.set_student_trade_updated_at();

drop trigger if exists set_student_trades_updated_at
  on public.student_trades;
create trigger set_student_trades_updated_at
before update on public.student_trades
for each row execute function public.set_student_trade_updated_at();

drop trigger if exists set_student_trade_comments_updated_at
  on public.student_trade_comments;
create trigger set_student_trade_comments_updated_at
before update on public.student_trade_comments
for each row execute function public.set_student_trade_updated_at();


insert into storage.buckets (
  id,
  name,
  public,
  file_size_limit,
  allowed_mime_types
)
values (
  'trade-journal-screenshots',
  'trade-journal-screenshots',
  false,
  10485760,
  array[
    'image/jpeg',
    'image/png',
    'image/webp',
    'image/gif'
  ]
)
on conflict (id) do update
set
  public = false,
  file_size_limit = 10485760,
  allowed_mime_types = excluded.allowed_mime_types;


drop policy if exists "Admins access all trade journal screenshots"
  on storage.objects;
create policy "Admins access all trade journal screenshots"
on storage.objects
for all
to authenticated
using (
  bucket_id = 'trade-journal-screenshots'
  and public.is_admin()
)
with check (
  bucket_id = 'trade-journal-screenshots'
  and public.is_admin()
);


drop policy if exists "Students read own trade journal screenshots"
  on storage.objects;
create policy "Students read own trade journal screenshots"
on storage.objects
for select
to authenticated
using (
  bucket_id = 'trade-journal-screenshots'
  and split_part(name, '/', 1) = auth.uid()::text
  and public.has_active_mentorship_access(auth.uid())
);


drop policy if exists "Students upload own trade journal screenshots"
  on storage.objects;
create policy "Students upload own trade journal screenshots"
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'trade-journal-screenshots'
  and split_part(name, '/', 1) = auth.uid()::text
  and public.has_active_mentorship_access(auth.uid())
);


drop policy if exists "Students delete own trade journal screenshots"
  on storage.objects;
create policy "Students delete own trade journal screenshots"
on storage.objects
for delete
to authenticated
using (
  bucket_id = 'trade-journal-screenshots'
  and split_part(name, '/', 1) = auth.uid()::text
  and public.has_active_mentorship_access(auth.uid())
);
