-- Diário de Trade — recursos para espelhar o Franco Performance
-- Execute depois de student_trade_journal.sql.
-- É idempotente e preserva todo o histórico existente.

alter table public.student_trades
  add column if not exists initial_risk numeric(18,2),
  add column if not exists duration_minutes integer,
  add column if not exists exit_reason text,
  add column if not exists exit_quality text,
  add column if not exists quick_review_completed boolean not null default false,
  add column if not exists quick_review jsonb not null default '{}'::jsonb;

create index if not exists student_trades_quick_review_idx
  on public.student_trades(student_id, quick_review_completed, trade_date desc);


create table if not exists public.student_trade_playbooks (
  id bigint generated by default as identity primary key,
  student_id uuid not null references public.profiles(id),
  name text not null,
  context text,
  entry_rule text,
  invalidation_rule text,
  management_rule text,
  exit_rule text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists student_trade_playbooks_student_idx
  on public.student_trade_playbooks(student_id, active, created_at desc);

alter table public.student_trade_playbooks enable row level security;

drop policy if exists "Playbooks private access" on public.student_trade_playbooks;
create policy "Playbooks private access"
on public.student_trade_playbooks for select to authenticated
using (public.can_access_student_trade_journal(student_id));

drop policy if exists "Playbooks private insert" on public.student_trade_playbooks;
create policy "Playbooks private insert"
on public.student_trade_playbooks for insert to authenticated
with check (
  public.can_access_student_trade_journal(student_id)
  and (public.is_admin() or student_id = auth.uid())
);

drop policy if exists "Playbooks private update" on public.student_trade_playbooks;
create policy "Playbooks private update"
on public.student_trade_playbooks for update to authenticated
using (public.can_access_student_trade_journal(student_id))
with check (
  public.can_access_student_trade_journal(student_id)
  and (public.is_admin() or student_id = auth.uid())
);

drop policy if exists "Playbooks private delete" on public.student_trade_playbooks;
create policy "Playbooks private delete"
on public.student_trade_playbooks for delete to authenticated
using (
  public.can_access_student_trade_journal(student_id)
  and (public.is_admin() or student_id = auth.uid())
);


create table if not exists public.student_open_positions (
  id bigint generated by default as identity primary key,
  student_id uuid not null references public.profiles(id),
  account_id bigint references public.student_trade_accounts(id) on delete set null,
  symbol text not null,
  side text not null default 'long' check (side in ('long','short')),
  quantity numeric(18,4),
  entry_price numeric(18,6),
  stop_price numeric(18,6),
  initial_risk numeric(18,2),
  group_name text,
  notes text,
  opened_at timestamptz not null default now(),
  status text not null default 'open' check (status in ('open','closed')),
  closed_at timestamptz,
  exit_price numeric(18,6),
  pnl numeric(18,2),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists student_open_positions_student_idx
  on public.student_open_positions(student_id, status, opened_at desc);

alter table public.student_open_positions enable row level security;

drop policy if exists "Open positions private access" on public.student_open_positions;
create policy "Open positions private access"
on public.student_open_positions for select to authenticated
using (public.can_access_student_trade_journal(student_id));

drop policy if exists "Open positions private insert" on public.student_open_positions;
create policy "Open positions private insert"
on public.student_open_positions for insert to authenticated
with check (
  public.can_access_student_trade_journal(student_id)
  and (public.is_admin() or student_id = auth.uid())
);

drop policy if exists "Open positions private update" on public.student_open_positions;
create policy "Open positions private update"
on public.student_open_positions for update to authenticated
using (public.can_access_student_trade_journal(student_id))
with check (
  public.can_access_student_trade_journal(student_id)
  and (public.is_admin() or student_id = auth.uid())
);

drop policy if exists "Open positions private delete" on public.student_open_positions;
create policy "Open positions private delete"
on public.student_open_positions for delete to authenticated
using (
  public.can_access_student_trade_journal(student_id)
  and (public.is_admin() or student_id = auth.uid())
);


create table if not exists public.student_weekly_reviews (
  id bigint generated by default as identity primary key,
  student_id uuid not null references public.profiles(id),
  week_start date not null,
  summary text,
  best_trade text,
  worst_trade text,
  main_error text,
  adjustment text,
  observable_criterion text,
  focus_setup text,
  weekly_goal text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(student_id, week_start)
);

create index if not exists student_weekly_reviews_student_idx
  on public.student_weekly_reviews(student_id, week_start desc);

alter table public.student_weekly_reviews enable row level security;

drop policy if exists "Weekly reviews private access" on public.student_weekly_reviews;
create policy "Weekly reviews private access"
on public.student_weekly_reviews for select to authenticated
using (public.can_access_student_trade_journal(student_id));

drop policy if exists "Weekly reviews private insert" on public.student_weekly_reviews;
create policy "Weekly reviews private insert"
on public.student_weekly_reviews for insert to authenticated
with check (
  public.can_access_student_trade_journal(student_id)
  and (public.is_admin() or student_id = auth.uid())
);

drop policy if exists "Weekly reviews private update" on public.student_weekly_reviews;
create policy "Weekly reviews private update"
on public.student_weekly_reviews for update to authenticated
using (public.can_access_student_trade_journal(student_id))
with check (
  public.can_access_student_trade_journal(student_id)
  and (public.is_admin() or student_id = auth.uid())
);

drop policy if exists "Weekly reviews private delete" on public.student_weekly_reviews;
create policy "Weekly reviews private delete"
on public.student_weekly_reviews for delete to authenticated
using (
  public.can_access_student_trade_journal(student_id)
  and (public.is_admin() or student_id = auth.uid())
);


create table if not exists public.student_prop_payouts (
  id bigint generated by default as identity primary key,
  student_id uuid not null references public.profiles(id),
  account_id bigint not null references public.student_trade_accounts(id) on delete cascade,
  requested_at date not null default current_date,
  amount numeric(18,2) not null check (amount > 0),
  status text not null default 'pending' check (status in ('pending','paid','canceled')),
  paid_at date,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists student_prop_payouts_student_idx
  on public.student_prop_payouts(student_id, account_id, requested_at desc);

alter table public.student_prop_payouts enable row level security;

drop policy if exists "Payouts private access" on public.student_prop_payouts;
create policy "Payouts private access"
on public.student_prop_payouts for select to authenticated
using (public.can_access_student_trade_journal(student_id));

drop policy if exists "Payouts private insert" on public.student_prop_payouts;
create policy "Payouts private insert"
on public.student_prop_payouts for insert to authenticated
with check (
  public.can_access_student_trade_journal(student_id)
  and (public.is_admin() or student_id = auth.uid())
);

drop policy if exists "Payouts private update" on public.student_prop_payouts;
create policy "Payouts private update"
on public.student_prop_payouts for update to authenticated
using (public.can_access_student_trade_journal(student_id))
with check (
  public.can_access_student_trade_journal(student_id)
  and (public.is_admin() or student_id = auth.uid())
);

drop policy if exists "Payouts private delete" on public.student_prop_payouts;
create policy "Payouts private delete"
on public.student_prop_payouts for delete to authenticated
using (
  public.can_access_student_trade_journal(student_id)
  and (public.is_admin() or student_id = auth.uid())
);


drop trigger if exists set_student_trade_playbooks_updated_at on public.student_trade_playbooks;
create trigger set_student_trade_playbooks_updated_at
before update on public.student_trade_playbooks
for each row execute function public.set_student_trade_updated_at();

drop trigger if exists set_student_open_positions_updated_at on public.student_open_positions;
create trigger set_student_open_positions_updated_at
before update on public.student_open_positions
for each row execute function public.set_student_trade_updated_at();

drop trigger if exists set_student_weekly_reviews_updated_at on public.student_weekly_reviews;
create trigger set_student_weekly_reviews_updated_at
before update on public.student_weekly_reviews
for each row execute function public.set_student_trade_updated_at();

drop trigger if exists set_student_prop_payouts_updated_at on public.student_prop_payouts;
create trigger set_student_prop_payouts_updated_at
before update on public.student_prop_payouts
for each row execute function public.set_student_trade_updated_at();
