-- FrancoTrades — Análises de Trades (imagem + explicação)
-- Execute este arquivo uma única vez no SQL Editor do Supabase.
-- Regras:
-- 1) Mentor administra uma biblioteca global de análises com imagem.
-- 2) Aluno só acessa após as 8 primeiras aulas estarem liberadas.
-- 3) O acesso às análises em imagem termina no momento em que a última sessão
--    contratada (12ª ou 13ª) for liberada.
-- 4) As imagens ficam em bucket PRIVADO e respeitam a mesma regra de elegibilidade.

create or replace function public.can_access_trade_analysis_reviews()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles p
    where p.id = auth.uid()
      and p.role = 'aluno'
      and p.status = 'ativo'
      and (
        p.data_expiracao is null
        or p.data_expiracao >= current_date
      )
      and (
        select count(distinct s.numero)
        from public.student_sessions ss
        join public.sessions s
          on s.id = ss.session_id
        where ss.student_id = p.id
          and ss.liberada = true
          and s.numero between 1 and 8
      ) = 8
      and not exists (
        select 1
        from public.student_sessions ss_last
        join public.sessions s_last
          on s_last.id = ss_last.session_id
        where ss_last.student_id = p.id
          and ss_last.liberada = true
          and s_last.numero = greatest(
            12,
            coalesce(
              (
                select mf.quantidade_sessoes
                from public.mentorship_financials mf
                where
                  mf.profile_id = p.id
                  or lower(coalesce(mf.email, '')) = lower(coalesce(p.email, ''))
                order by
                  case when mf.profile_id = p.id then 0 else 1 end,
                  mf.id
                limit 1
              ),
              12
            ),
            coalesce(
              (
                select max(s_contract.numero)
                from public.student_sessions ss_contract
                join public.sessions s_contract
                  on s_contract.id = ss_contract.session_id
                where ss_contract.student_id = p.id
              ),
              0
            )
          )
      )
  );
$$;

create table if not exists public.trade_analysis_reviews (
  id bigint generated by default as identity primary key,
  titulo text not null,
  explicacao text not null,
  image_path text not null,
  ativo boolean not null default true,
  published_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.trade_analysis_reviews enable row level security;

drop policy if exists "Admins gerenciam analises de trades"
  on public.trade_analysis_reviews;

create policy "Admins gerenciam analises de trades"
on public.trade_analysis_reviews
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Alunos elegiveis visualizam analises de trades"
  on public.trade_analysis_reviews;

create policy "Alunos elegiveis visualizam analises de trades"
on public.trade_analysis_reviews
for select
to authenticated
using (
  ativo = true
  and public.can_access_trade_analysis_reviews()
);

create or replace function public.set_trade_analysis_reviews_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_trade_analysis_reviews_updated_at
  on public.trade_analysis_reviews;

create trigger set_trade_analysis_reviews_updated_at
before update on public.trade_analysis_reviews
for each row
execute function public.set_trade_analysis_reviews_updated_at();

create index if not exists trade_analysis_reviews_active_published_idx
on public.trade_analysis_reviews (ativo, published_at desc);

insert into storage.buckets (
  id,
  name,
  public,
  file_size_limit,
  allowed_mime_types
)
values (
  'trade-review-images',
  'trade-review-images',
  false,
  5242880,
  array[
    'image/jpeg',
    'image/png',
    'image/webp',
    'image/gif'
  ]
)
on conflict (id) do update
set
  public = false,
  file_size_limit = 5242880,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Admins gerenciam imagens das analises"
  on storage.objects;

create policy "Admins gerenciam imagens das analises"
on storage.objects
for all
to authenticated
using (
  bucket_id = 'trade-review-images'
  and public.is_admin()
)
with check (
  bucket_id = 'trade-review-images'
  and public.is_admin()
);

drop policy if exists "Alunos elegiveis visualizam imagens das analises"
  on storage.objects;

create policy "Alunos elegiveis visualizam imagens das analises"
on storage.objects
for select
to authenticated
using (
  bucket_id = 'trade-review-images'
  and public.can_access_trade_analysis_reviews()
);
