-- FrancoTrades — progresso individual nas Revisões dos Trades
-- Execute este arquivo uma única vez no SQL Editor do Supabase.
--
-- Cada mentorado pode marcar como concluída:
-- • uma análise com imagem (analysis)
-- • uma revisão em vídeo (video)
--
-- O progresso é individual e persiste mesmo se o conteúdo deixar de ficar visível.

create table if not exists public.trade_review_progress (
  id bigint generated by default as identity primary key,
  student_id uuid not null references public.profiles(id) on delete cascade,
  review_type text not null check (review_type in ('analysis', 'video')),
  review_id bigint not null,
  concluida boolean not null default true,
  updated_at timestamptz not null default now(),
  unique (student_id, review_type, review_id)
);

alter table public.trade_review_progress enable row level security;

drop policy if exists "Alunos gerenciam proprio progresso de revisoes"
  on public.trade_review_progress;

create policy "Alunos gerenciam proprio progresso de revisoes"
on public.trade_review_progress
for all
to authenticated
using (
  student_id = auth.uid()
)
with check (
  student_id = auth.uid()
);

drop policy if exists "Admins visualizam progresso de revisoes"
  on public.trade_review_progress;

create policy "Admins visualizam progresso de revisoes"
on public.trade_review_progress
for select
to authenticated
using (
  public.is_admin()
);

create index if not exists trade_review_progress_student_idx
  on public.trade_review_progress(student_id, review_type, review_id);
