-- FrancoTrades — Revisão dos Trades
-- Execute este arquivo uma vez no SQL Editor do Supabase.
-- Cria uma biblioteca global de vídeos, administrada pelo mentor.
-- Alunos ativos só conseguem ler os vídeos depois que existirem gravações das 8 primeiras aulas.

create table if not exists public.trade_reviews (
  id bigint generated by default as identity primary key,
  titulo text not null,
  descricao text,
  youtube_url text not null,
  ativo boolean not null default true,
  published_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.trade_reviews enable row level security;

drop policy if exists "Admins gerenciam revisoes de trades" on public.trade_reviews;
create policy "Admins gerenciam revisoes de trades"
on public.trade_reviews
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Alunos elegiveis visualizam revisoes de trades" on public.trade_reviews;
create policy "Alunos elegiveis visualizam revisoes de trades"
on public.trade_reviews
for select
to authenticated
using (
  ativo = true
  and exists (
    select 1
    from public.profiles p
    where p.id = auth.uid()
      and p.role = 'aluno'
      and p.status = 'ativo'
      and (
        p.data_expiracao is null
        or p.data_expiracao >= current_date
      )
  )
  and (
    select count(distinct s.id)
    from public.sessions s
    join public.student_sessions ss
      on ss.session_id = s.id
     and ss.student_id = auth.uid()
    where s.numero between 1 and 8
      and nullif(btrim(coalesce(ss.youtube_url, '')), '') is not null
  ) = 8
);

create or replace function public.set_trade_reviews_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_trade_reviews_updated_at on public.trade_reviews;
create trigger set_trade_reviews_updated_at
before update on public.trade_reviews
for each row
execute function public.set_trade_reviews_updated_at();

create index if not exists trade_reviews_active_published_idx
on public.trade_reviews (ativo, published_at desc);
