import test from 'node:test';import assert from 'node:assert/strict';
import {parseTradeEdit,renderTradeEditor} from '../aluno/diario-de-trade/modules/trade-edit.js';
const accounts=[{id:1,name:'Minha conta',active:true},{id:2,name:'Arquivada',active:false}];
const trade={id:7,account_id:1,initial_risk:100,quick_review:{note:'Original',execution:{checks:{setup:true,risk:true,stop:true,exit:true},psychology:{actualRisk:100,acceptance:8},growth:{plan:{stop:'Preservar'},pauses:[{id:'p'}]}}}};
const fields=()=>new Map(Object.entries({account_id:'1',trade_date:'2026-10-07',symbol:'mes',side:'long',quantity:'2',pnl:'200',fees:'5',initial_risk:'50',setup:'Pullback',notes:'Correção'}));
test('Edits compute gross RR and synchronize risk while preserving execution and original plan',()=>{const before=JSON.stringify(trade),p=parseTradeEdit(fields(),trade,accounts);assert.equal(p.rr,4);assert.equal(p.initial_risk,50);assert.equal(p.quick_review.execution.psychology.actualRisk,50);assert.deepEqual(p.quick_review.execution.growth,trade.quick_review.execution.growth);assert.deepEqual(p.quick_review.execution.checks,trade.quick_review.execution.checks);assert.equal(p.quick_review.note,'Original');assert.equal(p.symbol,'MES');assert.equal(p.entry_price,null);assert.equal(JSON.stringify(trade),before);assert(!('source'in p));assert(!('quick_review_completed'in p))});
test('Clearing risk yields unknown RR and retains unrelated data',()=>{const f=fields();f.set('initial_risk','');const p=parseTradeEdit(f,trade,accounts);assert.equal(p.rr,null);assert.equal(p.initial_risk,null);assert.equal(p.quick_review.execution.psychology.actualRisk,null);f.set('initial_risk','100');assert(!('quick_review'in parseTradeEdit(f,trade,accounts)))});
test('Rejects invalid numbers, invalid dates and changes to archived or missing accounts',()=>{for(const [key,value]of [['quantity','0'],['fees','-1'],['pnl','Infinity'],['trade_date','2026-02-30'],['account_id','2'],['account_id','3'],['symbol',''],['side','invalid']]){const f=fields();f.set(key,value);assert.throws(()=>parseTradeEdit(f,trade,accounts))}const f=fields();f.set('account_id','2');assert.equal(parseTradeEdit(f,{...trade,account_id:2},accounts).account_id,2)});
test('Editor escapes user values and includes the current archived account',()=>{const html=renderTradeEditor({...trade,account_id:2,symbol:'<script>',notes:'</textarea><script>bad</script>'},accounts,'detail-1');assert(html.includes('&lt;script&gt;'));assert(!html.includes('<script>'));assert(html.includes('Arquivada'));assert(html.includes('name="pnl"'));assert(html.includes('name="initial_risk"'));assert(html.includes('data-save-trade-edit'))});
