import {CRITERIA,ACTIONS,REDUCTIONS,COACH_NAME,execution,checks,status,ordered,summary,curves,tolerance,decodeCoach,protocol,experiment,signature,ladder,missionStats,management,acted,risk,net} from './execution-core.js';
const escape=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
const format=(n,suffix='')=>n==null?'Pendente':Number(n).toLocaleString('pt-BR',{maximumFractionDigits:1})+suffix;
const help=text=>`<details class="exec-help"><summary aria-label="Explicação">?</summary><p>${escape(text)}</p></details>`;
const field=(label,input,hint='')=>`<div class="field"><div class="exec-field-label"><span>${escape(label)}</span>${hint?help(hint):''}</div>${input}</div>`;
const input=(name,value='',type='text',extra='')=>`<input aria-label="${escape(name)}" name="${name}" type="${type}" value="${escape(value??'')}" ${extra}>`;
const area=(name,value='',extra='')=>`<textarea aria-label="${escape(name)}" name="${name}" rows="2" maxlength="2000" ${extra}>${escape(value)}</textarea>`;
function select(name,value,options){return `<select name="${name}" aria-label="${name}">${options.map(([v,label])=>`<option value="${escape(v)}" ${String(value??'')===String(v)?'selected':''}>${escape(label)}</option>`).join('')}</select>`;}
const yesno=(name,v)=>select(name,typeof v==='boolean'?(v?'yes':'no'):'',[['','Não avaliado'],['yes','Sim'],['no','Não']]);
const rating=(name,value)=>select(name,value,[['','Não avaliado'],...Array.from({length:11},(_,i)=>[i,String(i)])]);
const number=(f,k,min=0,max=1e10)=>{const raw=f.get(k);if(raw==null||String(raw).trim()==='')return null;const n=Number(raw);if(!Number.isFinite(n)||n<min||n>max)throw Error('Confira o valor de '+k+'.');return n;};
const answer=(f,k)=>f.get(k)==='yes'?true:f.get(k)==='no'?false:null;
const text=(f,k)=>String(f.get(k)||'').trim();
const card=(label,value,note,explanation)=>`<article class="exec-card"><div class="exec-field-label"><span>${label}</span>${help(explanation)}</div><strong>${value}</strong><small>${note}</small></article>`;
export function createExecutionTools(api){
 let coach=decodeCoach([]).state,coachRecord=null,windowSize=10,tab='protocol',charts=[],saving=false,reviewBusy=false;
 const $=id=>document.getElementById(id),state=()=>api.state(),readOnly=()=>state().mentorView;
 const all=()=>state().trades,filtered=()=>api.filteredTrades(),currency=ts=>{const cs=[...new Set(ts.map(t=>state().accounts.find(a=>String(a.id)===String(t.account_id))?.currency||'USD'))];return cs.length>1?null:cs[0]||'USD';};
 const money=(n,ts=filtered())=>currency(ts)?api.money(n,currency(ts)):'Moedas distintas';
 const tradeById=id=>all().find(t=>String(t.id)===String(id));
 function message(error){api.showMessage(error.message||String(error),'error');}
 function button(action,label,id='',primary=false){return `<button type="button" class="btn ${primary?'primary':''}" data-exec-action="${action}" data-exec-id="${escape(id)}">${label}</button>`;}
 function submit(label){return readOnly()?'':`<div class="actions"><button class="btn primary" type="submit">${label}</button></div>`;}
 function coachForm(id,content,label){return `<form id="${id}" class="exec-form" ${readOnly()?'data-readonly':''}>${content}${submit(label)}</form>`;}
 function psychologyFields(t={},prefix=''){
  const e=execution(t),p=e.psychology||{},growth=e.growth||{};return `<fieldset class="exec-fieldset"><legend>Risco, desconforto e gestão</legend><div class="grid2">
${field('Aceitação do risco · 0–10',rating('acceptance',p.acceptance),'0: não aceito perder o risco integral. 10: confortável em tomar o stop planejado. Não depende do resultado.')}
${field('Desconforto máximo · 0–10',rating('discomfort',p.discomfort),'Maior desconforto durante a posição. Vontade de interferir não é a mesma coisa que alterar a gestão.')}
${field('Risco planejado',input('plannedRisk',p.plannedRisk,'number','min="0" step="0.01"'),'Valor que decidiu aceitar antes da entrada, na moeda da conta. Não é o prejuízo realizado.')}
${field('Risco realmente utilizado na entrada',input('actualRisk',p.actualRisk??t.initial_risk,'number','min="0" step="0.01"'),'Risco inicial da posição, antes de mover o stop. Atualiza o denominador de R; zero não comprova operação sem risco.')}
${field('Quantidade planejada',input('plannedQty',p.plannedQty,'number','min="0.0001" step="any"'),'Quantidade pretendida antes da operação. A quantidade executada continua no registro do trade.')}
${field('Se atingir o stop, a entrada continua correta?',yesno('stopAccepted',p.stopAccepted),'Avalie a decisão de entrar independentemente de ganhar ou perder.')}
${field('Nível de risco',select('riskLevelId',p.riskLevelId||(!t.id?coach.activeLevelId:''),[['','Não atribuído'],...coach.levels.map(l=>[l.id,l.name])]),'Atribuição manual. Trocar o nível ativo não muda operações antigas.')}
${field('Motivo de usar menos quantidade',select('reductionReason',p.reductionReason,[['','Não avaliado'],...REDUCTIONS.map(x=>[x,x])]),'Só entra na análise de redução se a quantidade executada for menor que a planejada. Uma redução prevista não é automaticamente um erro.')}
${field('Detalhe do motivo',area('reductionNote',p.reductionNote||''))}
${field('Plano e aceitação definidos antes da entrada?',yesno('recordedBefore',p.recordedBefore),'É uma declaração sua. Dados preenchidos depois são reconstrução retrospectiva.')}
${field('Teve vontade de interferir?',yesno('urge',p.urge),'Sentir vontade e não agir pode ser um exemplo de boa execução.')}
${field('Realmente alterou a gestão?',yesno('intervened',p.intervened),'Inclui alterações técnicas previstas. A justificativa abaixo classifica a ação.')}</div>
<div data-exec-conditional="urge"><b>O que teve vontade de fazer?</b><div class="exec-checks">${ACTIONS.map(a=>`<label><input type="checkbox" name="urges" value="${a}" ${p.urges?.includes(a)?'checked':''}>${a}</label>`).join('')}</div></div>
<div data-exec-conditional="intervened"><b>O que realmente fez?</b><div class="exec-checks">${ACTIONS.map(a=>`<label><input type="checkbox" name="actions" value="${a}" ${p.actions?.includes(a)?'checked':''}>${a}</label>`).join('')}</div>
${field('Todas as alterações tinham condição técnica prevista?',yesno('technical',p.technical),'Marque sim apenas se a condição já constava no plano. Sem descrição, a classificação permanece pendente.')}
<div data-exec-conditional="technical">${field('Qual condição técnica ocorreu?',area('technicalCondition',p.technicalCondition||''))}</div>
<div data-exec-conditional="motive">${field('Motivo da alteração não prevista',select('motive',p.motive||'Não avaliado',[['Não avaliado','Não avaliado'],['Emocional','Aliviar desconforto / emocional'],['Outro','Outro motivo']]))}</div></div></fieldset>
<details class="exec-details"><summary>Missão e boas execuções</summary>${growth.mission?`<p class="section-note">${escape(growth.mission.text)}</p>${field('Cumpri a missão?',select('missionResult',growth.missionResult||'pending',[['pending','Pendente'],['yes','Sim'],['no','Não'],['na','Não se aplicou']]))}`:coach.mission?`<label><input name="linkMission" type="checkbox" ${!t.id?'checked':''}>Vincular à missão atual: ${escape(coach.mission.text)}</label>`:'<p>Defina uma missão no protocolo de 20 trades.</p>'}<label><input type="checkbox" name="highlight" ${growth.highlight?'checked':''}>Guardar na galeria de boas execuções, inclusive se foi loss</label>${field('O que me ajudou a seguir o plano?',area('helped',growth.helped||''))}</details>`;
 }
 function readPsychology(f,previous={},fallback=null){
  const urge=answer(f,'urge'),intervened=answer(f,'intervened'),technical=intervened===true?answer(f,'technical'):null,acceptance=number(f,'acceptance',0,10),discomfort=number(f,'discomfort',0,10);if([acceptance,discomfort].some(v=>v!=null&&!Number.isInteger(v)))throw Error('As escalas de aceitação e desconforto vão de 0 a 10, em números inteiros.');
  return {...previous,acceptance,discomfort,plannedRisk:number(f,'plannedRisk'),actualRisk:number(f,'actualRisk')??fallback,plannedQty:number(f,'plannedQty',0.0001),stopAccepted:answer(f,'stopAccepted'),recordedBefore:answer(f,'recordedBefore')===true,reductionReason:text(f,'reductionReason')||null,reductionNote:text(f,'reductionNote'),riskLevelId:text(f,'riskLevelId'),urge,urges:urge===true?f.getAll('urges').filter(x=>ACTIONS.includes(x)):[],intervened,actions:intervened===true?f.getAll('actions').filter(x=>ACTIONS.includes(x)):[],technical,technicalCondition:technical===true?text(f,'technicalCondition'):'',motive:technical===false?text(f,'motive')||'Não avaliado':'Não avaliado'};
 }
 function readGrowth(f,prior={}){return {...prior,...(!prior.mission&&f.get('linkMission')&&coach.mission?{mission:{...coach.mission},missionResult:'pending'}:{}),...(prior.mission?{missionResult:text(f,'missionResult')||'pending'}:{}),highlight:f.get('highlight')==='on',helped:text(f,'helped')};}
 function planFields(){return `<div class="grid2">${field('Risco integral aceito',input('planRisk','','number','min="0.01" step="0.01" required'))}${field('Aceitação emocional · 0–10',rating('planAcceptance',''))}${[['stop','Stop / condição de invalidação'],['target','Alvo / critério de saída'],['be','Condição exata que autoriza break-even'],['changes','Outras mudanças permitidas']].map(([k,label])=>field(label,area('plan_'+k,'','required'),'Descreva uma condição objetiva ou escreva “Nenhuma”.')).join('')}</div><label><input type="checkbox" name="planBefore">Defini este plano antes da entrada</label><p class="muted">O registro original fica preservado. A declaração de horário não substitui o registro antes de operar.</p>`;}
 function readPlan(f){const acceptance=number(f,'planAcceptance',0,10),amount=number(f,'planRisk',0.01);if(acceptance==null||!Number.isInteger(acceptance)||amount==null)throw Error('Informe risco positivo e aceitação de 0 a 10.');const p={savedAt:new Date().toISOString(),beforeEntry:f.get('planBefore')==='on',risk:amount,acceptance};for(const k of ['stop','target','be','changes']){p[k]=text(f,'plan_'+k);if(!p[k])throw Error('Preencha todas as condições do plano original.');}return p;}
 function planView(g={}){const p=g.plan;return p?`<div class="exec-original"><b>Plano original · ${new Date(p.savedAt).toLocaleString('pt-BR')}</b><p>${p.beforeEntry?'Declarado como definido antes da entrada':'Registro durante a posição / retrospectivo'}</p><div class="grid2">${[['Risco integral',format(p.risk)],['Aceitação',p.acceptance+'/10'],['Stop',p.stop],['Alvo',p.target],['Regra de BE',p.be],['Mudanças permitidas',p.changes]].map(([k,v])=>`<div><small>${k}</small><p>${escape(v)}</p></div>`).join('')}</div></div>`:'<p class="muted">Sem plano original registrado.</p>';}
 async function saveCoach(next){if(readOnly())throw Error('Acompanhamento do mentor: visualização.');if(saving)throw Error('Aguarde o salvamento anterior.');saving=true;try{const payload={student_id:state().studentId,name:COACH_NAME,context:JSON.stringify(next),active:false};const q=coachRecord?api.supabase.from('student_trade_playbooks').update(payload).eq('id',coachRecord.id).eq('student_id',state().studentId):api.supabase.from('student_trade_playbooks').insert(payload);const {data,error}=await q.select('*').single();if(error)throw error;coach=next;coachRecord=data;if($('tradeFormWrap').classList.contains('hidden'))resetNew();render();api.showMessage('Acompanhamento de execução salvo.');}finally{saving=false;}}
 async function saveReview(t,f){if(readOnly())return;const previous=execution(t),p=readPsychology(f,previous.psychology,Number(t.initial_risk)>0?Number(t.initial_risk):null),updated={...previous,version:1,checks:Object.fromEntries(Object.keys(CRITERIA).map(k=>[k,answer(f,'check_'+k)])),psychology:p,growth:readGrowth(f,previous.growth)};
  const temp={...t,quick_review:{...t.quick_review,execution:updated}},qr={...t.quick_review,execution:updated,stop_respected:updated.checks.stop==null?'':updated.checks.stop?'yes':'no',risk_respected:updated.checks.risk==null?'':updated.checks.risk?'yes':'no',note:text(f,'reviewNote')};
  const actual=p.actualRisk,payload={quick_review:qr,quick_review_completed:status(temp).complete,exit_reason:text(f,'exitReason')||t.exit_reason||null,exit_quality:text(f,'exitQuality')||t.exit_quality||null};if(actual!=null){payload.initial_risk=actual;payload.rr=actual>0?Number(t.pnl||0)/actual:null;}
  const {error}=await api.supabase.from('student_trades').update(payload).eq('id',t.id).eq('student_id',state().studentId);if(error)throw error;await api.reload();$('executionDialog').close();api.showMessage('Revisão da execução salva.');
 }
 function syncConditional(form){if(!form)return;const v=name=>form.querySelector(`[name="${name}"]`)?.value;for(const el of form.querySelectorAll('[data-exec-conditional]')){const kind=el.dataset.execConditional,show=kind==='urge'?v('urge')==='yes':kind==='intervened'?v('intervened')==='yes':kind==='technical'?v('intervened')==='yes'&&v('technical')==='yes':v('intervened')==='yes'&&v('technical')==='no';el.hidden=!show;}}
 function mountNewFields(){$('executionNewFields')?.remove();const actions=$('saveTradeButton').closest('.actions');actions.insertAdjacentHTML('beforebegin','<form id="executionNewFields" class="exec-form">'+psychologyFields()+'<details class="exec-details"><summary>Registrar plano original · opcional</summary><p class="muted">Para registrar antes de operar, utilize Posições abertas. Neste registro, indique se está reconstruindo a decisão.</p>'+planFields().replaceAll('required','')+'</details></form>');syncConditional($('executionNewFields'));}
 function readNewTrade(){const f=new FormData($('executionNewFields')),fallback=Number($('tradeRisk').value)>0?Number($('tradeRisk').value):null,p=readPsychology(f,{},fallback),growth=readGrowth(f);if(text(f,'planRisk')||text(f,'plan_stop')||text(f,'plan_target')||text(f,'plan_be')||text(f,'plan_changes'))growth.plan=readPlan(f);return {version:1,checks:{setup:null,risk:null,stop:null,exit:null},psychology:p,growth};}
 function resetNew(){mountNewFields();}
 function showDialog(title,content){const d=$('executionDialog');$('executionDialogTitle').textContent=title;$('executionDialogBody').innerHTML=content;syncConditional(d.querySelector('form'));if(readOnly())d.querySelectorAll('input,select,textarea').forEach(el=>el.disabled=true);if(!d.open)d.showModal();}
 function openReview(id){const t=tradeById(id);if(!t)return;const e=execution(t),s=status(t);showDialog('Execução · '+t.symbol+' · '+t.trade_date,`<p class="section-note">Score ${s.score??'Pendente'} · ${s.answered}/4 avaliados · lucro ou prejuízo não altera a pontuação.</p><form id="executionReviewForm" data-trade-id="${t.id}" class="exec-form"><div class="grid2">${Object.entries(CRITERIA).map(([k,label])=>field(label+' · 25 pontos',yesno('check_'+k,checks(t)[k]),'Sim: 25 pontos. Não: 0. A nota final só existe após os quatro critérios serem avaliados.')).join('')}</div>${psychologyFields(t)}${planView(e.growth)}<details class="exec-details"><summary>Saída e aprendizado</summary><div class="grid2">${field('Motivo da saída',select('exitReason',t.exit_reason||'',[['','Não informado'],...['Alvo','Stop','Saída discricionária','Saída antecipada','Tempo','Erro operacional'].map(x=>[x,x])]))}${field('Qualidade da execução',select('exitQuality',t.exit_quality||'',[['','Não informado'],...['Boa','Regular','Ruim'].map(x=>[x,x])]))}</div>${field('Aprendizado da revisão',area('reviewNote',t.quick_review?.note||''))}</details>${e.growth?.pauses?.length?`<details><summary>${e.growth.pauses.length} pausas registradas</summary>${e.growth.pauses.map(p=>`<p>${escape(p.at)} · ${p.discomfort}/10 · ${escape(p.changed)} · ${escape(p.decision)}</p>`).join('')}</details>`:''}${submit('Salvar revisão completa')}</form>`);}
 function table(rows,head){return `<div class="table-wrap"><table><thead><tr>${head.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${rows.length?rows.map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join('')}</tr>`).join(''):`<tr><td colspan="${head.length}">Sem dados neste recorte.</td></tr>`}</tbody></table></div>`;}
 function comparison(rows){return table(rows.map(s=>[escape(s.label),s.count,format(s.score)+`<small>${s.reviewed} avaliações completas</small>`,format(s.r,'R')+`<small>${s.rN} riscos conhecidos</small>`,format(s.interference,'%')+`<small>${s.interferenceN} avaliados</small>`,format(s.stop.value,'%')+`<small>${s.stop.n} avaliados</small>`,format(s.exit.value,'%')+`<small>${s.exit.n} avaliados</small>`]),['Grupo','Trades','Execution Score','Expectativa líquida em R','Interferências','Stop respeitado','Gestão respeitada']);}
 function checkpointHtml(ts){return [5,10,20,30].map(n=>{const s=summary(ordered(ts).slice(-n));return `<button type="button" class="exec-checkpoint ${windowSize===n?'selected':''}" data-exec-action="window" data-exec-id="${n}" aria-pressed="${windowSize===n}"><span>ÚLTIMOS ${n} TRADES<small>${s.reviewed} avaliados / ${s.count} disponíveis</small></span><span class="exec-ring" style="--score:${s.score??0}"><b>${s.score==null?'—':format(s.score)}</b><small>/100</small></span></button>`;}).join('');}
 function evolutionHtml(ts,prefix){const mixed=currency(ts)==null,s=summary(ts);return `<section class="panel exec-evolution"><div class="panel-head"><div><div class="eyebrow">Painel de evolução</div><h2>Seu processo em movimento ${help('Setup, risco, stop e gestão valem 25 pontos cada. A média ignora avaliações incompletas. P&L não altera a nota.')}</h2><p class="muted">Resultado financeiro e qualidade da execução, lado a lado.</p></div><span class="pill">${s.reviewed}/${ts.length} revisados</span></div><div class="exec-checkpoints">${checkpointHtml(ts)}</div>${!ts.length?'<div class="empty">Registre e revise o primeiro trade para iniciar sua evolução.</div>':`<div class="grid2"><div class="exec-chart"><h3>Resultado financeiro</h3><strong>${money(s.pnl,ts)}</strong>${mixed?'<p>Selecione uma conta ou contas na mesma moeda para somar resultados.</p>':`<div class="chart-box"><canvas id="${prefix}Money"></canvas></div>`}</div><div class="exec-chart"><h3>Qualidade da execução</h3><strong>${format(s.score)} <small>/100</small></strong><div class="chart-box"><canvas id="${prefix}Score"></canvas></div></div></div>`}<p class="exec-note">Média móvel de ${windowSize} trades. Pendentes aparecem como lacunas; a média usa só revisões completas na janela. O eixo segue a sequência dos trades selecionados.</p></section>`;}
 function renderCharts(ts,prefix){if(!ts.length)return;const data=curves(ts,windowSize),color=getComputedStyle(document.documentElement).getPropertyValue('--muted').trim(),grid='rgba(125,150,140,.14)';for(const [key,suffix,line] of [['financial','Money',data.at(-1)?.financial<0?'#ff6b78':'#43e290'],['score','Score','#78b7ff']]){const canvas=$(prefix+suffix);if(!canvas)continue;const ctx=canvas.getContext('2d'),fill=ctx.createLinearGradient(0,0,0,260);fill.addColorStop(0,key==='score'?'rgba(120,183,255,.28)':'rgba(67,226,144,.25)');fill.addColorStop(1,'rgba(67,226,144,0)');charts.push(new Chart(canvas,{type:'line',data:{labels:data.map(d=>'#'+d.index),datasets:[{label:key==='score'?'Execution Score':'P&L líquido acumulado',data:data.map(d=>d[key]),borderColor:line,backgroundColor:fill,fill:true,borderWidth:3,pointRadius:data.length<40?4:0,pointBackgroundColor:line,tension:0,spanGaps:false}]},options:{responsive:true,maintainAspectRatio:false,animation:false,plugins:{legend:{display:false},tooltip:{callbacks:{title:items=>data[items[0]?.dataIndex]?.label||'',afterLabel:item=>key==='score'?`${data[item.dataIndex].reviewed}/${data[item.dataIndex].sample} avaliados na janela`:''}}},scales:{x:{ticks:{color,maxTicksLimit:8},grid:{display:false}},y:{min:key==='score'?0:Math.min(0,...data.map(d=>d.financial)),max:key==='score'?100:undefined,ticks:{color,stepSize:key==='score'?25:undefined},grid:{color:grid}}}}}));}}
 function protocolHtml(){const ts=protocol(all(),coach),s=summary(ts),x=experiment(ts),ms=missionStats(ts,coach.mission?.id),missing=coach.protocolIds.length-ts.length;return `<section class="panel"><h2>20 trades de execução ${help('Você seleciona até 20 trades de um bloco. Apenas scores completos entram na média. O sucesso do processo não é medido somente pelo lucro.')}</h2><p class="muted">${ts.length}/20 operações · ${s.reviewed}/20 revisões completas${missing?' · '+missing+' registros indisponíveis':''}. O protocolo usa todos os trades escolhidos, independentemente dos filtros globais.</p><div class="exec-progress"><i style="width:${Math.min(100,ts.length/20*100)}%"></i></div><div class="exec-metrics">${card('Score do bloco',format(s.score),s.reviewed+' completos','Média das notas completas, sem transformar pendentes em zero.')}${card('Execuções de 100 pontos',format(s.perfect,'%'),s.reviewed+' avaliados','Percentual de scores 100 entre avaliações completas.')}${card('Aceitação média',format(s.acceptance,'/10'),'Percepção registrada','Média das respostas preenchidas.')}${card('Desconforto médio',format(s.discomfort,'/10'),'Percepção registrada','Não avaliado fica fora da média.')}</div>
${!readOnly()?`<details class="exec-details"><summary>Escolher os trades do bloco</summary><form id="execProtocolForm"><div class="exec-selection">${ordered(all()).reverse().map(t=>`<label><input type="checkbox" name="tradeIds" value="${t.id}" ${coach.protocolIds.map(String).includes(String(t.id))?'checked':''}>${escape(t.trade_date)} · ${escape(t.symbol)} · ${escape(t.setup||'Sem setup')} · score ${status(t).score??'pendente'}</label>`).join('')}</div>${submit('Salvar seleção do bloco')}</form></details>`:''}${table(ordered(ts).map(t=>[escape(t.trade_date)+' · '+escape(t.symbol),status(t).score??'Pendente',`${execution(t).psychology?.plannedQty??'—'} / ${t.quantity??'—'}`,`${execution(t).psychology?.plannedRisk??'—'} / ${risk(t)??'—'}`,management(t),button('review',readOnly()?'Ver avaliação':'Revisar',t.id)]),['Trade','Score','Quantidade planejada / executada','Risco planejado / utilizado','Gestão','Avaliação'])}</section>
<section class="panel"><h2>Uma missão para o bloco</h2>${coach.mission?`<p class="section-note">${escape(coach.mission.text)}</p><p>${format(ms.percent,'%')} de cumprimento · ${ms.yes}/${ms.assessed} avaliações aplicáveis · ${ms.pending} pendentes · ${ms.na} não se aplicam · ${ms.linked} vinculados.</p>`:'<p>Escolha um único comportamento observável, como manter o stop até ocorrer a condição técnica.</p>'}${readOnly()?'':coachForm('execMissionForm',field('Missão observável',area('mission',coach.mission?.text||'Só mover para break-even quando a condição registrada no plano ocorrer.','required maxlength="600"')),'Salvar nova missão')}</section>
${evolutionHtml(ts,'execProtocol')}
<section class="panel"><h2>Fechamento do experimento</h2><p>${x.complete}/20 avaliações completas. ${x.ready?'Revise o padrão e escolha um ajuste para o próximo bloco.':'Disponível após 20 trades com os quatro critérios avaliados.'}</p>${table(x.rows.map(r=>[r.label,r.no,r.n]),['Critério','Não cumpridos','Avaliados'])}${x.patterns.length?`<p>Maior frequência de descumprimento: ${x.patterns.map(r=>r.label).join(', ')}. Isso descreve as respostas, sem identificar a causa automaticamente.</p>`:''}${x.ready&&!readOnly()?coachForm('execConclusionForm',field('Minha conclusão',area('conclusion',coach.conclusion?.signature===signature(ts)?coach.conclusion.text:'','required'))+field('Um ajuste para o próximo bloco',area('next',coach.conclusion?.signature===signature(ts)?coach.conclusion.nextAction:'','required')),'Confirmar conclusão e ajuste'):''}${coach.conclusion?`<div class="section-note"><b>${coach.conclusion.signature===signature(ts)?'Conclusão confirmada':'Conclusão anterior · dados ou seleção mudaram'}</b><p>${escape(coach.conclusion.text)}</p><p>Próximo ajuste: ${escape(coach.conclusion.nextAction)}</p></div>`:''}</section>`;}
 function toleranceHtml(){const ts=filtered(),reduced=ts.filter(t=>execution(t).psychology?.plannedQty>Number(t.quantity)&&Number(t.quantity)>0);return `<section class="panel"><h2>Aceitação do risco</h2>${comparison(tolerance(ts,'acceptance'))}<p class="exec-note">${ts.filter(t=>execution(t).psychology?.acceptance==null).length} trades sem avaliação. Grupos pequenos são pistas para revisão, não uma relação de causa e efeito.</p></section><section class="panel"><h2>Desconforto máximo</h2>${comparison(tolerance(ts,'discomfort'))}</section><section class="panel"><h2>Execução por risco utilizado</h2>${currency(ts)==null?'<p>Selecione uma conta para comparar valores na mesma moeda.</p>':`<label class="field">Intervalo de risco<input id="execRiskBand" type="number" min="0.01" step="0.01" value="${riskBand}"></label>${comparison([{label:'Até '+money(riskBand),...summary(ts.filter(t=>risk(t)>0&&risk(t)<=riskBand))},{label:money(riskBand)+' a '+money(riskBand*2),...summary(ts.filter(t=>risk(t)>riskBand&&risk(t)<=riskBand*2))},{label:'Acima de '+money(riskBand*2),...summary(ts.filter(t=>risk(t)>riskBand*2))}])}`}<p class="exec-note">Risco ausente ou zero fica fora dos grupos. Esta análise não recomenda aumentar posições.</p></section><section class="panel"><h2>Por que usou menos quantidade?</h2>${comparison([...REDUCTIONS,'Não avaliado'].map(label=>({label,...summary(reduced.filter(t=>(execution(t).psychology?.reductionReason||'Não avaliado')===label))})))}</section>`;}
 let riskBand=50;
 function exitHtml(){const ts=filtered(),be=ts.filter(t=>acted(t,ACTIONS[0])),early=ts.filter(t=>acted(t,ACTIONS[2]));return `<section class="panel"><h2>Gestão da saída</h2><div class="exec-metrics">${card('Moveu para BE',be.length,'Ação realizada','Vontade de mover não conta como ação.')}${card('BE técnico previsto',be.filter(t=>management(t)==='Técnica prevista').length,'Condição descrita','Requer condição prevista e descrição do que ocorreu.')}${card('BE emocional',be.filter(t=>management(t)==='Emocional').length,'Motivo declarado','Não previsto e feito para aliviar desconforto.')}${card('Saídas antes do alvo',early.length,'Ação realizada','Saídas antecipadas podem ter justificativa técnica prevista.')}</div>${comparison([{label:'Gestão respeitada',...summary(ts.filter(t=>checks(t).exit===true&&management(t)!=='Emocional'))},{label:'Interferência emocional',...summary(ts.filter(t=>management(t)==='Emocional'))},{label:'Técnica prevista',...summary(ts.filter(t=>management(t)==='Técnica prevista'))}])}<p class="exec-note">${ts.filter(t=>execution(t).psychology?.intervened==null).length} trades sem avaliação de interferência. Ajustes técnicos previstos não são classificados como emocionais.</p></section><section class="panel"><h2>Realizado / MFE ${help('Resultado bruto dividido pelo MFE bruto positivo. Pode ser negativo. MFE não representa lucro garantido nem o movimento após a saída.')}</h2>${table(ordered(ts.filter(t=>Number(t.mfe)>0)).reverse().map(t=>[escape(t.trade_date)+' · '+escape(t.symbol),money(t.pnl,[t]),money(t.mfe,[t]),format(Number(t.pnl)/Number(t.mfe)*100,'%')]),['Trade','Resultado bruto','MFE positivo','Realizado / MFE'])}</section>`;}
 function ladderHtml(){return `<section class="panel"><h2>Escada manual de risco</h2><p class="exec-note">Avalia os últimos N trades vinculados a cada nível, sem filtros globais. Nenhum tamanho é aumentado automaticamente. Configure níveis para instrumentos comparáveis e na mesma moeda.</p><div class="grid2">${coach.levels.map(l=>{const st=ladder(all(),l);return `<article class="exec-level"><h3>${escape(l.name)} ${l.id===coach.activeLevelId?'<span class="pill pos">Ativo</span>':''}</h3><p>Risco máximo: ${l.risk??'não definido'} · quantidade máxima: ${l.maxQty??'não definida'}</p><p>${st.s.count}/${l.minTrades} trades · ${st.s.reviewed} revisados · score ${format(st.s.score)} / ${l.minScore} · aderência ${format(st.s.perfect,'%')} / ${l.minAdherence}%</p><b>${st.ready?'Critérios atingidos para avaliar o próximo nível.':'Critérios não atingidos ou dados pendentes.'}</b>${!readOnly()?button('level','Escolher este nível manualmente',l.id):''}</article>`;}).join('')}</div>${!readOnly()?`<details class="exec-details"><summary>Configurar níveis</summary>${coachForm('execLadderForm',coach.levels.map(l=>`<fieldset><legend>${escape(l.name)}</legend><div class="grid2">${field('Nome / instrumento',input(l.id+'_name',l.name,'text','required maxlength="80"'))}${field('Risco máximo por trade',input(l.id+'_risk',l.risk,'number','min="0.01" step="any"'))}${field('Quantidade máxima',input(l.id+'_qty',l.maxQty,'number','min="0.0001" step="any"'))}${field('Mínimo de trades',input(l.id+'_trades',l.minTrades,'number','min="1" max="1000" required'))}${field('Score mínimo',input(l.id+'_score',l.minScore,'number','min="0" max="100" required'))}${field('Aderência mínima · % scores 100',input(l.id+'_adherence',l.minAdherence,'number','min="0" max="100" required'))}</div></fieldset>`).join(''),'Salvar níveis')}</details>`:''}<details><summary>Histórico das escolhas manuais</summary>${coach.levelHistory.length?coach.levelHistory.slice().reverse().map(h=>`<p>${escape(h.date)} · ${escape(coach.levels.find(l=>l.id===h.levelId)?.name||h.levelId)}</p>`).join(''):'<p>Nenhuma escolha registrada.</p>'}</details></section>`;}
 function galleryHtml(){const saved=all().filter(t=>execution(t).growth?.highlight),candidates=all().filter(t=>!execution(t).growth?.highlight&&status(t).score===100&&execution(t).psychology?.urge===true&&execution(t).psychology?.intervened===false);return `<section class="panel"><h2>Galeria de boas execuções</h2><p class="exec-note">Gains e losses têm o mesmo espaço. A seleção usa todos os trades e não altera o score.</p><div class="grid2">${saved.map(t=>`<article class="exec-example"><div class="exec-example-image" data-exec-image-trade="${t.id}"></div><h3>${escape(t.symbol)} · ${escape(t.trade_date)}</h3><span class="pill">Score ${status(t).score??'Pendente'}</span><p>${escape(execution(t).growth?.helped||'Sem relato do que ajudou.')}</p><p>Resultado: ${money(net(t),[t])} · desconforto ${execution(t).psychology?.discomfort??'não avaliado'}/10</p>${button('review',readOnly()?'Ver avaliação':'Revisar exemplo',t.id)}</article>`).join('')||'<p>Na revisão de execução, marque os exemplos que deseja revisitar.</p>'}</div>${candidates.length?`<details><summary>${candidates.length} candidatos · score 100 com vontade, sem interferir</summary>${candidates.map(t=>`<p>${escape(t.trade_date)} · ${escape(t.symbol)} ${button('review','Revisar exemplo',t.id)}</p>`).join('')}</details>`:''}</section>`;}
 function analysisHtml(){const ts=filtered(),groups=fn=>[...new Set(ts.map(fn))].map(label=>({label,...summary(ts.filter(t=>fn(t)===label))}));return `<section class="panel"><h2>Execution Score por setup</h2>${comparison(groups(t=>t.setup||'Sem setup'))}</section><section class="panel"><h2>Execution Score por ativo</h2>${comparison(groups(t=>t.symbol||'Sem ativo'))}</section><section class="panel"><h2>Execution Score por estado emocional</h2>${comparison(groups(t=>t.emotion||'Não informado'))}</section><section class="panel"><h2>Análise das operações</h2>${table(ordered(ts).reverse().map(t=>[escape(t.trade_date)+' · '+escape(t.symbol),money(net(t),[t]),status(t).score??'Pendente',format(execution(t).psychology?.acceptance,'/10'),format(execution(t).psychology?.discomfort,'/10'),management(t),button('review',readOnly()?'Ver avaliação':'Avaliar',t.id)]),['Trade','Resultado líquido','Score','Aceitação','Desconforto','Gestão','Revisão'])}</section>`;}
 function render(){charts.forEach(c=>c.destroy());charts=[];const ts=filtered();$('executionOverview').innerHTML=evolutionHtml(ts,'execOverview');renderCharts(ts,'execOverview');const host=$('executionDevelopment');if(!host)return;host.innerHTML=`<div class="exec-objective"><div class="eyebrow">Desenvolvimento de execução</div><h2>Seguir o processo, aceitar o risco e revisar as decisões</h2><p>Um loss dentro do plano pode ter score 100. Um gain com quebra de regras não recebe pontos pelo lucro.</p>${readOnly()?'<span class="pill">Acompanhamento do mentor</span>':''}</div><div class="exec-tabs">${[['protocol','Protocolo 20 trades'],['analysis','Análise dos trades'],['tolerance','Tolerância ao risco'],['exit','Gestão da saída'],['ladder','Escada de risco'],['gallery','Boas execuções']].map(([k,label])=>`<button class="btn ${tab===k?'primary':''}" data-exec-action="tab" data-exec-id="${k}" aria-pressed="${tab===k}">${label}</button>`).join('')}</div>${tab==='protocol'?protocolHtml():tab==='analysis'?analysisHtml():tab==='tolerance'?toleranceHtml():tab==='exit'?exitHtml():tab==='ladder'?ladderHtml():galleryHtml()}`;if(tab==='protocol')renderCharts(protocol(all(),coach),'execProtocol');refreshBadges();renderPositionTools();if(tab==='gallery')renderGalleryImages();}
 function refreshBadges(){for(const b of document.querySelectorAll('[data-trade-detail]')){if(b.parentElement.querySelector('[data-exec-action="review"]'))continue;const t=tradeById(b.dataset.tradeDetail);if(t){const actions=document.createElement('div');actions.className='exec-trade-actions';b.before(actions);actions.append(b);actions.insertAdjacentHTML('afterbegin',button('review','Score '+(status(t).score??'pendente'),t.id));}}}
 function renderQuick(){const list=filtered().filter(t=>!status(t).complete);$('quickReviewList').innerHTML=list.length?list.map(t=>`<article class="review-card"><b>${escape(t.trade_date)} · ${escape(t.symbol)}</b><p>${status(t).answered}/4 critérios avaliados · ${management(t)}</p>${button('review','Avaliar execução',t.id,true)}</article>`).join(''):'<div class="empty">Todas as operações deste recorte têm os quatro critérios avaliados.</div>';$('quickPendingBadge').textContent=list.length+' pendentes';$('navQuickCount').textContent=list.length;$('navQuickCount').classList.toggle('hidden',!list.length);}
 function renderPositionTools(){for(const card of document.querySelectorAll('#openPositionsList .position-card')){if(card.querySelector('[data-exec-action="position"]'))continue;const ref=card.querySelector('[data-close-position]');if(ref)card.insertAdjacentHTML('beforeend',button('position',readOnly()?'Ver plano e pausas':'Meu plano · pausa antes de interferir',ref.dataset.closePosition));}}
 async function renderGalleryImages(){const nodes=[...document.querySelectorAll('[data-exec-image-trade]')];for(const el of nodes){const attachment=state().attachments.find(a=>String(a.trade_id)===String(el.dataset.execImageTrade));if(!attachment)continue;const url=await api.signedUrl(attachment.storage_path);if(url&&el.isConnected){const image=document.createElement('img');image.src=url;image.alt='Print de uma boa execução';image.loading='lazy';el.replaceChildren(image);}}}
 function positionDialog(id){const position=state().positions.find(p=>String(p.id)===String(id));if(!position)return;const g=coach.positionPlans?.[id]||{},pauseForm=`<form id="execPauseForm" data-position-id="${id}" class="exec-form"><h3>Consulte seu plano antes de decidir</h3>${field('Desconforto agora · 0–10',rating('pauseDiscomfort',''))}${field('O que mudou no mercado?',area('changed','','required'),'Pode ser “Nada mudou, estou desconfortável”.')}${field('A condição prevista aconteceu?',select('condition','',[['','Selecione'],['yes','Sim'],['no','Não'],['unsure','Incerta / sem plano']]))}${field('Qual é sua decisão?',select('decision','Manter o plano',['Manter o plano','Aplicar condição prevista','Outra decisão'].map(x=>[x,x])))}<p class="exec-note">A pausa registra a reflexão. A ação realizada será confirmada na revisão. Nenhuma ordem é alterada ou bloqueada.</p>${submit('Registrar pausa e decisão')}</form>`;showDialog('Plano de execução · '+position.symbol,`${planView(g)}${!g.plan&&!readOnly()?`<details open><summary>Definir plano original</summary><form id="execPositionPlan" data-position-id="${id}" class="exec-form">${planFields()}${submit('Salvar plano original')}</form></details>`:''}<details class="exec-details"><summary>Estou com vontade de interferir</summary>${pauseForm}</details>${g.pauses?.length?`<details><summary>${g.pauses.length} pausas registradas</summary>${g.pauses.slice().reverse().map(p=>`<p>${escape(p.at)} · desconforto ${p.discomfort}/10<br>${escape(p.changed)}<br>${escape(p.decision)} · condição ${p.condition==='yes'?'ocorreu':p.condition==='no'?'não ocorreu':'incerta'}</p>`).join('')}</details>`:''}`);}
 async function closePosition(id,exit,pnl,fees=0){if(readOnly())return;const p=state().positions.find(x=>String(x.id)===String(id));if(!p)return;const g=coach.positionPlans?.[id]||{};let existing=all().find(t=>String(execution(t).sourcePositionId)===String(id));if(!existing){const executionData={version:1,sourcePositionId:String(id),checks:{setup:null,risk:null,stop:null,exit:null},growth:{...g},psychology:{acceptance:g.plan?.acceptance??null,plannedRisk:g.plan?.risk??null,actualRisk:Number(p.initial_risk)>0?Number(p.initial_risk):null,recordedBefore:g.plan?.beforeEntry||false,riskLevelId:g.riskLevelId||''}};const {data,error}=await api.supabase.from('student_trades').insert({student_id:state().studentId,account_id:p.account_id,trade_date:api.today(),symbol:p.symbol,side:p.side,quantity:p.quantity,entry_price:p.entry_price,exit_price:exit===''?null:Number(exit),pnl:Number(pnl),fees:Number(fees),initial_risk:p.initial_risk,rr:Number(p.initial_risk)>0?Number(pnl)/Number(p.initial_risk):null,notes:p.notes,source:'manual',quick_review:{execution:executionData},quick_review_completed:false}).select('id').single();if(error)throw error;existing=data;}
 const {error}=await api.supabase.from('student_open_positions').update({status:'closed',closed_at:new Date().toISOString(),exit_price:exit===''?null:Number(exit),pnl:Number(pnl)}).eq('id',id).eq('student_id',state().studentId);if(error){await api.reload();throw Error('Trade registrado, mas a posição não foi encerrada. Tente encerrar novamente; o trade não será duplicado.');}await api.reload();api.showMessage('Posição encerrada e trade registrado. Revise a execução.');}
 document.addEventListener('click',async event=>{const b=event.target.closest('[data-exec-action]');if(!b)return;const action=b.dataset.execAction,id=b.dataset.execId;try{if(action==='review')openReview(id);else if(action==='position')positionDialog(id);else if(action==='window'){windowSize=Number(id);render();}else if(action==='tab'){tab=id;render();}else if(action==='close')$('executionDialog').close();else if(action==='level'&&!readOnly())await saveCoach({...coach,activeLevelId:id,levelHistory:[...coach.levelHistory,{levelId:id,date:new Date().toISOString()}]});}catch(error){message(error);}});
 document.addEventListener('change',event=>{if(event.target.closest('.exec-form'))syncConditional(event.target.closest('form'));if(event.target.id==='execRiskBand'){const n=Number(event.target.value);if(n>0&&Number.isFinite(n)){riskBand=n;render();}}});
 document.addEventListener('submit',async event=>{const form=event.target;if(!form.id.startsWith('exec')&&form.id!=='executionReviewForm')return;event.preventDefault();if(readOnly()||saving||reviewBusy)return;const f=new FormData(form),buttons=[...form.querySelectorAll('button[type="submit"]')];buttons.forEach(b=>b.disabled=true);try{
 if(form.id==='executionReviewForm'){reviewBusy=true;try{await saveReview(tradeById(form.dataset.tradeId),f)}finally{reviewBusy=false;}}
 else if(form.id==='execProtocolForm'){const ids=f.getAll('tradeIds').map(String);if(ids.length>20)throw Error('Selecione no máximo 20 trades.');await saveCoach({...coach,protocolIds:ids});}
 else if(form.id==='execMissionForm'){const mission=text(f,'mission');if(!mission||mission.length>600)throw Error('A missão deve ter de 1 a 600 caracteres.');await saveCoach({...coach,mission:{id:crypto.randomUUID(),text:mission,createdAt:new Date().toISOString()}});}
 else if(form.id==='execConclusionForm'){const ts=protocol(all(),coach);if(!experiment(ts).ready)throw Error('Complete os 20 trades e as 20 avaliações antes de fechar o bloco.');await saveCoach({...coach,conclusion:{signature:signature(ts),text:text(f,'conclusion'),nextAction:text(f,'next'),confirmedAt:new Date().toISOString()}});}
 else if(form.id==='execLadderForm'){const levels=coach.levels.map(l=>({...l,name:text(f,l.id+'_name'),risk:number(f,l.id+'_risk',0.01),maxQty:number(f,l.id+'_qty',0.0001),minTrades:number(f,l.id+'_trades',1,1000),minScore:number(f,l.id+'_score',0,100),minAdherence:number(f,l.id+'_adherence',0,100)}));if(levels.some(l=>!l.name||!Number.isInteger(l.minTrades)||l.minScore==null||l.minAdherence==null))throw Error('Confira os critérios dos níveis.');await saveCoach({...coach,levels});}
 else if(form.id==='execPositionPlan'){const id=form.dataset.positionId,previous=coach.positionPlans?.[id]||{};if(previous.plan)throw Error('O plano original já está registrado.');await saveCoach({...coach,positionPlans:{...coach.positionPlans,[id]:{...previous,plan:readPlan(f),...(coach.mission?{mission:{...coach.mission},missionResult:'pending'}:{}),riskLevelId:coach.activeLevelId}}});positionDialog(id);}
 else if(form.id==='execPauseForm'){const id=form.dataset.positionId,discomfort=number(f,'pauseDiscomfort',0,10),condition=text(f,'condition');if(discomfort==null||!Number.isInteger(discomfort)||!['yes','no','unsure'].includes(condition))throw Error('Informe desconforto e se a condição ocorreu.');const prior=coach.positionPlans?.[id]||{};await saveCoach({...coach,positionPlans:{...coach.positionPlans,[id]:{...prior,pauses:[...(prior.pauses||[]),{id:crypto.randomUUID(),at:new Date().toISOString(),discomfort,changed:text(f,'changed'),condition,decision:text(f,'decision')}]}}});positionDialog(id);}
 }catch(error){message(error);}finally{buttons.forEach(b=>b.disabled=false);}});
 return {mount(){mountNewFields();},load(rows){const decoded=decodeCoach(rows);coach=decoded.state;coachRecord=decoded.record;if($('tradeFormWrap').classList.contains('hidden'))resetNew();return decoded.playbooks;},render,renderQuick,readNewTrade,resetNew,closePosition,status,openReview};
}
