export const CRITERIA={setup:'Segui o setup',risk:'Respeitei o risco',stop:'Respeitei o stop',exit:'Respeitei a gestão/saída'};
export const ACTIONS=['Moveu stop para BE','Aproximou stop','Saiu antes do alvo','Realizou parcial não planejada','Reduziu posição','Outro'];
export const REDUCTIONS=['Gestão de risco prevista','Regra da prop firm','Condição de mercado','Medo de perder','Desconforto com o valor financeiro','Falta de confiança no setup','Outro'];
export const COACH_NAME='__execution_coaching_v1__';
export function execution(t){return t?.quick_review?.execution||{};}
export function checks(t){const old=t?.quick_review||{},e=execution(t);return {...{setup:null,risk:old.risk_respected==='yes'?true:old.risk_respected==='no'?false:null,stop:old.stop_respected==='yes'?true:old.stop_respected==='no'?false:null,exit:null},...e.checks};}
export function status(t){const known=Object.keys(CRITERIA).map(k=>checks(t)[k]).filter(v=>typeof v==='boolean'),approved=known.filter(Boolean).length;return {answered:known.length,approved,score:known.length===4?approved*25:null,complete:known.length===4};}
export const ordered=ts=>[...ts].sort((a,b)=>String(a.trade_date).localeCompare(String(b.trade_date))||Number(a.id)-Number(b.id));
export const avg=vs=>{const valid=vs.filter(v=>v!=null&&Number.isFinite(v));return valid.length?valid.reduce((a,b)=>a+b,0)/valid.length:null;};
export const rate=(n,total)=>total?n/total*100:null;
export const net=t=>Number(t.pnl||0)-Number(t.fees||0);
export function risk(t){const v=execution(t).psychology?.actualRisk??t.initial_risk;return v!=null&&Number(v)>0?Number(v):null;}
export function management(t){const p=execution(t).psychology;if(!p||typeof p.intervened!=='boolean')return 'Pendente';if(!p.intervened)return 'Sem alteração';if(p.technical===true)return p.technicalCondition?.trim()?'Técnica prevista':'Pendente';if(p.technical===false&&p.motive==='Emocional')return 'Emocional';if(p.technical===false&&p.motive==='Outro')return 'Outra alteração';return 'Pendente';}
export function acted(t,a){const p=execution(t).psychology;return p?.intervened===true&&p.actions?.includes(a);}
export function summary(ts){
 const scores=ts.map(t=>status(t).score),complete=scores.filter(s=>s!==null),interventions=ts.filter(t=>typeof execution(t).psychology?.intervened==='boolean'),known=interventions.filter(t=>!execution(t).psychology.intervened||execution(t).psychology.actions?.length),tech=known.filter(t=>!execution(t).psychology.intervened||typeof execution(t).psychology.technical==='boolean'),riskTrades=ts.filter(t=>risk(t)>0),qtyPairs=ts.filter(t=>execution(t).psychology?.plannedQty>0&&t.quantity>0),riskPairs=ts.filter(t=>execution(t).psychology?.plannedRisk>0&&risk(t)>0);
 const criterion=k=>{const assessed=ts.filter(t=>typeof checks(t)[k]==='boolean');return {value:rate(assessed.filter(t=>checks(t)[k]).length,assessed.length),n:assessed.length};};
 return {count:ts.length,score:avg(scores),reviewed:complete.length,perfect:rate(complete.filter(s=>s===100).length,complete.length),pnl:ts.reduce((s,t)=>s+net(t),0),r:avg(riskTrades.map(t=>net(t)/risk(t))),rN:riskTrades.length,interference:rate(interventions.filter(t=>execution(t).psychology.intervened).length,interventions.length),interferenceN:interventions.length,emotional:ts.filter(t=>management(t)==='Emocional').length,beUnplanned:rate(tech.filter(t=>acted(t,ACTIONS[0])&&execution(t).psychology.technical===false).length,tech.length),early:rate(known.filter(t=>acted(t,ACTIONS[2])).length,known.length),acceptance:avg(ts.map(t=>execution(t).psychology?.acceptance)),discomfort:avg(ts.map(t=>execution(t).psychology?.discomfort)),qtyRatio:avg(qtyPairs.map(t=>Number(t.quantity)/execution(t).psychology.plannedQty*100)),riskRatio:avg(riskPairs.map(t=>risk(t)/execution(t).psychology.plannedRisk*100)),stop:criterion('stop'),exit:criterion('exit')};
}
export function curves(ts,window=10){let total=0;return ordered(ts).map((t,i,list)=>{total+=net(t);const sample=list.slice(Math.max(0,i-window+1),i+1),s=summary(sample);return {id:t.id,label:t.trade_date+' · '+t.symbol,index:i+1,financial:Math.round(total*100)/100,score:status(t).complete?s.score:null,reviewed:s.reviewed,sample:sample.length};});}
export function tolerance(ts,key){return [[0,3],[4,6],[7,8],[9,10]].map(([min,max])=>({label:min+'–'+max,...summary(ts.filter(t=>{const v=execution(t).psychology?.[key];return v!=null&&v>=min&&v<=max;}))}));}
export function defaultCoach(){return {version:1,protocolIds:[],mission:null,levels:[1,2,3,4].map(i=>({id:'level-'+i,name:'Nível '+i,risk:null,maxQty:null,minTrades:20,minScore:90,minAdherence:90})),activeLevelId:'',levelHistory:[],positionPlans:{}};}
export function decodeCoach(rows){const records=rows.filter(p=>p.name===COACH_NAME).sort((a,b)=>Number(a.id)-Number(b.id));const record=records[0]||null;let state={};try{state=record?JSON.parse(record.context||'{}'):{};}catch{}return {record,state:{...defaultCoach(),...state},playbooks:rows.filter(p=>p.name!==COACH_NAME)};}
export function protocol(ts,coach){return (coach.protocolIds||[]).map(id=>ts.find(t=>String(t.id)===String(id))).filter(Boolean);}
export function experiment(ts){const rows=Object.keys(CRITERIA).map(key=>({key,label:CRITERIA[key],no:ts.filter(t=>checks(t)[key]===false).length,n:ts.filter(t=>typeof checks(t)[key]==='boolean').length})),complete=ts.filter(t=>status(t).complete).length,max=Math.max(0,...rows.map(r=>r.no));return {rows,complete,ready:ts.length===20&&complete===20,patterns:rows.filter(r=>r.no===max&&max>0)};}
export function signature(ts){return JSON.stringify(ordered(ts).map(t=>[String(t.id),t.quick_review,t.pnl,t.fees,t.quantity,t.initial_risk]));}
export function ladder(ts,level){const linked=ordered(ts.filter(t=>execution(t).psychology?.riskLevelId===level.id)),sample=linked.slice(-level.minTrades),s=summary(sample),within=level.risk>0&&level.maxQty>0&&sample.every(t=>risk(t)>0&&risk(t)<=level.risk&&Number(t.quantity)>0&&Number(t.quantity)<=level.maxQty);return {s,total:linked.length,within,ready:sample.length>=level.minTrades&&s.reviewed===sample.length&&s.score>=level.minScore&&s.perfect>=level.minAdherence&&within};}
export function missionStats(ts,id){const linked=ts.filter(t=>id&&execution(t).growth?.mission?.id===id),assessed=linked.filter(t=>['yes','no'].includes(execution(t).growth?.missionResult)),yes=assessed.filter(t=>execution(t).growth.missionResult==='yes').length;return {linked:linked.length,assessed:assessed.length,yes,percent:rate(yes,assessed.length),pending:linked.filter(t=>!execution(t).growth?.missionResult||execution(t).growth.missionResult==='pending').length,na:linked.filter(t=>execution(t).growth?.missionResult==='na').length};}
