const escape=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
export function renderTradeEditor(t,accounts,prefix){
 const fields=[['trade_date','Data','date'],['symbol','Ativo','text'],['quantity','Quantidade / contratos','number'],['pnl','Resultado bruto (P&L)','number'],['fees','Taxas','number'],['entry_price','Preço de entrada','number'],['exit_price','Preço de saída','number'],['initial_risk','Risco inicial','number'],['duration_minutes','Duração em minutos','number'],['setup','Setup','text'],['emotion','Estado emocional','text'],['mfe','MFE','number'],['mae','MAE','number'],['exit_reason','Motivo da saída','text'],['exit_quality','Qualidade da saída','text']];
 const select=(name,label,options)=>`<div class="field"><label for="${prefix}-${name}">${label}</label><select id="${prefix}-${name}" name="${name}" required>${options}</select></div>`;
 const accountOptions=accounts.filter(a=>a.active||String(a.id)===String(t.account_id)).map(a=>`<option value="${a.id}" ${String(a.id)===String(t.account_id)?'selected':''}>${escape(a.name)}${a.active?'':' · arquivada'}</option>`).join('');
 return `<form data-trade-edit-form="${t.id}" class="trade-edit-form hidden"><h3>Editar operação</h3><div class="grid3">${select('account_id','Conta',accountOptions)}${select('side','Direção',['long','short'].map(v=>`<option value="${v}" ${String(t.side).toLowerCase()===v?'selected':''}>${v==='long'?'Long':'Short'}</option>`).join(''))}${fields.map(([name,label,type])=>`<div class="field"><label for="${prefix}-${name}">${label}</label><input id="${prefix}-${name}" name="${name}" type="${type}" ${type==='number'?'step="any"':''} ${['trade_date','symbol','pnl','fees'].includes(name)?'required':''} value="${escape(name==='trade_date'?String(t[name]||'').slice(0,10):t[name]??(name==='fees'?0:''))}"></div>`).join('')}<div class="field"><label>R:R automático · resultado bruto ÷ risco inicial</label><output data-edit-rr>${t.initial_risk>0?(Number(t.pnl||0)/Number(t.initial_risk)).toFixed(2)+'R':'—'}</output></div><div class="field full"><label for="${prefix}-notes">Observações / aprendizado</label><textarea id="${prefix}-notes" name="notes">${escape(t.notes)}</textarea></div></div><p class="muted">Resultado e risco usam a moeda da conta. Os prints e a revisão de execução continuam vinculados a esta operação.</p><div class="actions"><button type="submit" class="btn primary" data-save-trade-edit>Salvar alterações</button><button type="button" class="btn" data-cancel-trade-edit>Cancelar</button></div><p data-edit-error class="neg" role="alert"></p></form>`;
}
export function parseTradeEdit(f,t,accounts){
 const str=k=>String(f.get(k)??'').trim(),numeric=(k,{required=false,min=-Infinity}={})=>{const raw=str(k);if(!raw){if(required)throw Error('Preencha '+k+'.');return null;}const n=Number(raw);if(!Number.isFinite(n)||n<min)throw Error('Confira o valor de '+k+'.');return n;};
 const accountId=numeric('account_id',{required:true}),account=accounts.find(a=>Number(a.id)===accountId);if(!account||(!account.active&&String(t.account_id)!==String(account.id)))throw Error('Selecione uma conta válida.');
 const date=str('trade_date');if(!/^\d{4}-\d{2}-\d{2}$/.test(date)||Number.isNaN(Date.parse(date+'T00:00:00Z'))||new Date(date+'T00:00:00Z').toISOString().slice(0,10)!==date)throw Error('Informe uma data válida.');
 const symbol=str('symbol').toUpperCase(),side=str('side');if(!symbol||!['long','short'].includes(side))throw Error('Preencha ativo e direção.');
 const p={account_id:accountId,trade_date:date,symbol,side,quantity:numeric('quantity',{min:Number.MIN_VALUE}),pnl:numeric('pnl',{required:true}),fees:numeric('fees',{required:true,min:0}),entry_price:numeric('entry_price'),exit_price:numeric('exit_price'),initial_risk:numeric('initial_risk',{min:0}),duration_minutes:numeric('duration_minutes',{min:0}),mfe:numeric('mfe'),mae:numeric('mae'),setup:str('setup')||null,emotion:str('emotion')||null,notes:str('notes')||null,exit_reason:str('exit_reason')||null,exit_quality:str('exit_quality')||null};
 p.rr=p.initial_risk>0?p.pnl/p.initial_risk:null;
 if(p.initial_risk!==(t.initial_risk==null?null:Number(t.initial_risk))&&t.quick_review?.execution?.psychology){const qr=t.quick_review,e=qr.execution;p.quick_review={...qr,execution:{...e,psychology:{...e.psychology,actualRisk:p.initial_risk}}};}
 return p;
}
